from django.urls import path
from .views import (
    ProductListCreateView,
    ProductDetailView,
    CategoryListCreateView,
    CategoryDetailView,
    SimilarProductsView,
    WishlistListCreateView,
    WishlistRetrieveUpdateDestroyView,
    ProductReviewView,
    ProductImageListCreateView,
    ProductImageRetrieveUpdateDestroyView,
    ProductReviewRetrieveUpdateDestroyView,
    ProductExcelExportWithDropdownAPIView,
    SizeListCreateView,
    SizeRetrieveUpdateDestroyView,
    SubCategoryListCreateView,
    SubCategoryRetrieveUpdateDestroyView,
    ProductExcelImportAPIView,
    SubSubCategoryListCreateView,
    SubSubCategoryRetrieveUpdateDestroyView,
    CategoryExcelUploadView
)

urlpatterns = [
    path('products/', ProductListCreateView.as_view(), name='product-list-create'),
    path('products/<slug:slug>/similar/',
         SimilarProductsView.as_view(), name='similar-products'),
    path('products/<slug:subsubcategory_slug>/<slug:slug>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('images/', ProductImageListCreateView.as_view(),
         name='product-image-list-create'),
    path('images/<int:id>/', ProductImageRetrieveUpdateDestroyView.as_view(),
         name='product-image-retrieve-update-destroy'),
    path('categories/', CategoryListCreateView.as_view(),
         name='category-list-create'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('subcategories/', SubCategoryListCreateView.as_view(),
         name='subcategory-list-create'),
    path('subcategories/<slug:slug>/', SubCategoryRetrieveUpdateDestroyView.as_view(),
         name='subcategory-detail'),
    path('subsubcategories/', SubSubCategoryListCreateView.as_view(),
         name='subsubcategory-list-create'),
    path('subsubcategories/<slug:slug>/', SubSubCategoryRetrieveUpdateDestroyView.as_view(),
         name='subsubcategory-detail'),
    path('wishlist/', WishlistListCreateView.as_view(),
         name='wishlist-list-create'),
    path('wishlist/<int:id>/', WishlistRetrieveUpdateDestroyView.as_view(),
         name='wishlist-retrieve-update-destroy'),
    path('product-reviews/',
         ProductReviewView.as_view(), name='product-review'),
    path('product-reviews/<int:id>/', ProductReviewRetrieveUpdateDestroyView.as_view(),
         name='product-review-retrieve-update-destroy'),
    path('sizes/', SizeListCreateView.as_view(), name='size-list-create'),
    path('sizes/<int:id>/', SizeRetrieveUpdateDestroyView.as_view(),
         name='size-retrieve-update-destroy'),
    path('download/product-template/', ProductExcelExportWithDropdownAPIView.as_view(),
         name='product-template-download'),
    path('product/bulk-upload/',
         ProductExcelImportAPIView.as_view(), name='product-import'),
    path('category/bulk-upload/',
         CategoryExcelUploadView.as_view(), name='category-import'),
]
