# Generated by Django 5.2.1 on 2025-05-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
