# Generated by Django 5.2.1 on 2025-05-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
