# Generated by Django 5.2.1 on 2025-05-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_alt_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
