# Generated by Django 5.2.1 on 2025-05-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_image_alt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
    ]
