# Generated by Django 5.2.1 on 2025-05-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_market_price_alter_product_stock'),
        ('products', '0008_product_thumbnail_image'),
    ]

    operations = [
    ]
