# Generated by Django 5.2.1 on 2025-05-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
