# Generated by Django 5.2.1 on 2025-05-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20250525_1552'),
        ('products', '0010_alter_product_options_alter_product_unique_together'),
    ]

    operations = [
    ]
