# Generated by Django 5.2.1 on 2025-06-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_category_productsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'subcategory')},
        ),
    ]
