# Generated by Django 5.2.1 on 2025-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_color_size_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_alt_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
