# Generated by Django 5.2.1 on 2025-06-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_thumbnail_image_alt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
    ]
