# Generated by Django 5.2.1 on 2025-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_color_productimage_color_delete_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
    ]
