# Generated by Django 5.2.1 on 2025-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_color_alter_productimage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
