# Generated by Django 5.2.1 on 2025-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
