# Generated by Django 5.2.1 on 2025-06-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productsubsubcategory_product_subsubcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'subcategory', 'subsubcategory')},
        ),
    ]
