# Generated by Django 5.2.1 on 2025-06-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'subsubcategory')},
        ),
    ]
