# Generated by Django 5.2.1 on 2025-06-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_productsubcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubsubcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='products.productsubcategory'),
        ),
    ]
